#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/x43u/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &
#
eval $(gnome-keyring-daemon -s --components=pkcs11,secrets,ssh,gpg) &
sh ~/.fehbg &
xfce4-volumed &
thunar --daemon &
#nm-applet &
(sleep 4s && xfce4-power-manager) &
(sleep 6s && pnmixer) &
(sleep 8s && clipit) &
#(sleep 2s && conky -q) &
#(sleep 10s && plank) &
# Debian-local change:
#   - fbautostart has been added with a quick hack to check to see if it
#     exists. If it does, we'll start it up by default.
which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.
exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/x43u/.fluxbox/log"
